In [2]:
import numpy as np

In [ ]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10])
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(n1.ndim)

1


In [ ]:
data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(data.ndim)

2


In [7]:
n3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
n3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
print(n3.ndim)

3


In [9]:
data.sum()

78

In [10]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
data.shape

(3, 4)

In [14]:
data.reshape(6,2) # 3 * 4 = 12

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
array = np.array(data)

In [15]:
array.dtype

dtype('int32')

In [16]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
list = [1,2,3,4,5,6,7]
array = np.array(list)
print(array)

[1 2 3 4 5 6 7]


In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(1,5,10) #divid part

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.random.randn(2,5)

array([[ 1.64308581,  2.0229202 ,  1.15834252,  0.63983669,  1.45931831],
       [-0.19608491, -0.46669   ,  0.81601373,  1.04045336, -0.00377545]])

In [25]:
np.random.randint(1,100,10)

array([72, 50, 97, 61, 67, 43,  6, 50, 75, 22])

In [26]:
np.random.randint(1,50,10)

array([26, 22, 41, 37, 42, 37, 35, 11, 25, 42])

In [27]:
array = np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
array = np.random.randint(0,50,10)
array

array([34,  9, 32, 27, 30, 49, 41, 13,  2, 27])

In [33]:
array.reshape(2,5)

array([[34,  9, 32, 27, 30],
       [49, 41, 13,  2, 27]])

In [30]:
a = 51.5
b = 90
print(a+b)
print(type(a))
print(type(b))

141.5
<class 'float'>
<class 'int'>


In [31]:
import numpy as np


In [32]:
arr = np.array([[1.0,2.2,3.3],[4.3,5.3,6.3]])
print(arr)
print('Array is of type:',type(arr))
print('no. of dimensions:',arr.ndim)
print('shape of array :',arr.shape)
print('size of array:',arr.size)
print('array store element of type:',arr.dtype)

[[1.  2.2 3.3]
 [4.3 5.3 6.3]]
Array is of type: <class 'numpy.ndarray'>
no. of dimensions: 2
shape of array : (2, 3)
size of array: 6
array store element of type: float64
