In [1]:
import numpy as np

In [2]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10])
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
print(n1.ndim)

1


In [4]:
data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(data.ndim)

2


In [6]:
n3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
n3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
print(n3.ndim)

3


In [8]:
data.sum()

78

In [9]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
data.shape

(3, 4)

In [11]:
data.reshape(6,2) # 3 * 4 = 12

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [12]:
array = np.array(data)

In [13]:
array.dtype

dtype('int32')

In [14]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
list = [1,2,3,4,5,6,7]
array = np.array(list)
print(array)

[1 2 3 4 5 6 7]


In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(1,5,10) #divid part

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.randn(2,5)

array([[ 0.05988712, -0.62949227,  2.2177941 , -0.59582569, -0.50862635],
       [-0.22193241, -1.1020564 , -0.86579464, -0.78980642,  0.77937189]])

In [23]:
np.random.randint(1,100,10)

array([51, 53, 40, 38,  9, 52, 15, 13,  3, 17])

In [24]:
np.random.randint(1,50,10)

array([23, 46, 23, 47, 29, 29, 35, 17, 12, 28])

In [25]:
array = np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
array = np.random.randint(0,50,10)
array

array([49, 37, 41, 39, 48, 34, 17, 24,  3, 13])

In [27]:
array.reshape(2,5)

array([[49, 37, 41, 39, 48],
       [34, 17, 24,  3, 13]])

In [28]:
a = 51.5
b = 90
print(a+b)
print(type(a))
print(type(b))

141.5
<class 'float'>
<class 'int'>


In [29]:
import numpy as np


In [30]:
arr = np.array([[1.0,2.2,3.3],[4.3,5.3,6.3]])
print(arr)
print('Array is of type:',type(arr))
print('no. of dimensions:',arr.ndim)
print('shape of array :',arr.shape)
print('size of array:',arr.size)
print('array store element of type:',arr.dtype)

[[1.  2.2 3.3]
 [4.3 5.3 6.3]]
Array is of type: <class 'numpy.ndarray'>
no. of dimensions: 2
shape of array : (2, 3)
size of array: 6
array store element of type: float64
